<?php

namespace Database\Seeders;

use App\Models\Image;
use Illuminate\Database\Seeder;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $post_images = [
            [
                'post_id'=>1,
                'name'=>'01.jpg',
            ],
            [
                'post_id'=>1,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>1,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>1,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>1,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>1,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>1,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */

            [
                'post_id'=>2,
                'name'=>'02.jpg',
            ],
            [
                'post_id'=>2,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>2,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>2,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>2,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>2,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>2,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */

            [
                'post_id'=>3,
                'name'=>'03.jpg',
            ],
            [
                'post_id'=>3,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>3,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>3,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>3,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>3,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>3,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */
            [
                'post_id'=>4,
                'name'=>'04.jpg',
            ],
            [
                'post_id'=>4,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>4,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>4,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>4,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>4,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>4,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */

            [
                'post_id'=>5,
                'name'=>'05.jpg',
            ],
            [
                'post_id'=>5,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>5,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>5,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>5,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>5,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>5,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */

            [
                'post_id'=>6,
                'name'=>'06.png',
            ],
            [
                'post_id'=>6,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>6,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>6,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>6,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>6,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>6,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */
            
            [
                'post_id'=>7,
                'name'=>'07.jpeg',
            ],
            [
                'post_id'=>7,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>7,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>7,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>7,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>7,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>7,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */
            
            [
                'post_id'=>9,
                'name'=>'09.jpg',
            ],
            [
                'post_id'=>9,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>9,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>9,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>9,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>9,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>9,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */
            
            [
                'post_id'=>10,
                'name'=>'010.jpg',
            ],
            [
                'post_id'=>10,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>10,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>10,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>10,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>10,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>10,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */
            
            [
                'post_id'=>11,
                'name'=>'011.jpeg',
            ],
            [
                'post_id'=>11,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>11,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>11,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>11,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>11,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>11,
                'name'=>'106.jpg',
            ],



            /* ****************************************** */
            /* ****************************************** */
            /* ****************************************** */
            /* ****************************************** */




            [
                'post_id'=>12,
                'name'=>'01.jpg',
            ],
            [
                'post_id'=>12,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>12,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>12,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>12,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>12,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>12,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */

            [
                'post_id'=>13,
                'name'=>'02.jpg',
            ],
            [
                'post_id'=>13,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>13,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>13,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>13,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>13,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>13,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */

            [
                'post_id'=>14,
                'name'=>'03.jpg',
            ],
            [
                'post_id'=>14,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>14,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>14,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>14,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>14,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>14,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */
            [
                'post_id'=>15,
                'name'=>'04.jpg',
            ],
            [
                'post_id'=>15,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>15,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>15,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>15,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>15,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>15,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */

            [
                'post_id'=>16,
                'name'=>'05.jpg',
            ],
            [
                'post_id'=>16,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>16,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>16,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>16,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>16,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>16,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */

            [
                'post_id'=>17,
                'name'=>'06.png',
            ],
            [
                'post_id'=>17,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>17,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>17,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>17,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>17,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>17,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */
            
            [
                'post_id'=>18,
                'name'=>'07.jpeg',
            ],
            [
                'post_id'=>18,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>18,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>18,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>18,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>18,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>18,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */
            
            [
                'post_id'=>19,
                'name'=>'09.jpg',
            ],
            [
                'post_id'=>19,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>19,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>19,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>19,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>19,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>19,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */
            
            [
                'post_id'=>20,
                'name'=>'010.jpg',
            ],
            [
                'post_id'=>20,
                'name'=>'101.jpg',
            ],
            [
                'post_id'=>20,
                'name'=>'102.jpg',
            ],
            [
                'post_id'=>20,
                'name'=>'103.jpg',
            ],
            [
                'post_id'=>20,
                'name'=>'104.jpg',
            ],
            [
                'post_id'=>20,
                'name'=>'105.jpg',
            ],
            [
                'post_id'=>20,
                'name'=>'106.jpg',
            ],
            /* ****************************************** */

            
        ];

        Image::insert($post_images);
    }
}
